# This workflow will build a package using Maven
# For more information see: https://github.com/actions/setup-java#apache-maven-with-a-settings-path

name: Maven Package

on:
  push:
    branches: [BotInterface]
    paths-ignore:
    - ".github/**"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Maven
      run: mvn compile --file pom.xml
      
    - name: Merge branche Production
      # You may pin to the exact commit or the version.
      # uses: everlytic/branch-merge@43400784008f811a3400f7e165ca9de0a8998a0b
      uses: everlytic/branch-merge@1.1.0
      with:
        # Token used to authenticate with GitHub when performing the merge command.
        github_token: ${{ github.token }}
        # Branch name or Ref that you wish to merge into the target_branch.
        source_ref: ${{ github.ref }}
        # Branch you are merging the source ref into.
        target_branch: Production
        # Template to generate the commit message, see README.md for more info
        commit_message_template: Merge automatique de {source_ref} a {target_branch} par ${{ github.actor }}
